### ISSUE TITLE
Integrating within Ionic?

### ISSUE THREAD

**Issue by christianfl** [romgrk/web-toolkit#15]
Hi! The theme looks quite good so far. I thought it could make sense to integrate it within Ionic? This way we could write web applications (framework independent) which look decent on Android, iOS and GNOME/Phosh.

**Comment by romgrk** [comment]
No idea phosh existed, seems quite nice ^^

Regarding ionic integration, I feel a bit hesitant about that. Their components are already built so they're likely to already have their styling/theming done in a way that would be incompatible with this project. Also they seem to be focused on mobile PWAs, the focus of this project is rather for desktop web apps. I'm totally down to make it work for mobile but that's not my first concern.

I also fear that phosh usage is too limited to make the porting of its theme to ionic a viable project :/

**Comment by christianfl** [comment]
Yeah, I can totally understand that integrating is too much work as Ionic uses custom components and all of this theme would have to be completely customized to work with that... Maybe I find some time and can make a prototype by myself!

Concerning phosh, what do you mean by you fear that it could be too limited? Phosh uses the same Adwaita theme as desktop applications, the only difference is that the GTK apps need to use a library which is called libhandy - which offers some containers, etc. which are mobile adaptive. But of course, they work on desktop, too. :)

As of Gnome 3.38 there are many standard Gnome apps which use libhandy to work on mobile, e.g. the gnome system settings (try to make the window very tiny and have a look how it behaves!)

**Comment by romgrk** [comment]
Closing as it's out of scope for now.
