### ISSUE TITLE
Using with vanilla JS and HTML, will add into GrapeJS drag and drop builder

### ISSUE THREAD

**Issue by vini-ub** [romgrk/web-toolkit#21]
Hello! Is there a way to "un-react" these components? I will create a GTK/Adwaita components pack for GrapeJS drag and drop builder, so I thought I could leverage this project or at least some assets. 

Any suggestion on this? (:

**Comment by romgrk** [comment]
There is a single CSS file generated, you could re-use it. But there is no easy way to unreact those components. You can use them to see the required HTML structure for the CSS classes.
