### ISSUE TITLE
Split package

### ISSUE THREAD

**Issue by romgrk** [romgrk/web-toolkit#8]
We should split this into a multi-package repo:
 - web-toolkit: CSS/icons
 - web-toolkit-react: React implementation
 - web-toolkit-solid: (Very hypothetical) Solid implementation
 - web-toolkit-doc: Documentation/showcase website (private package)

**Comment by odama626** [comment]
I think this could be good to use instead of webpack / react scripts
https://github.com/developit/microbundle
and potentially use storybook as well
https://storybook.js.org/

**Comment by romgrk** [comment]
Closing as split is ok for now, further separation can be addressed if/when other implementations than the react one are started.
